---
name: Tag Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g., v1.2.3)'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
