---
name: Update Chart

on:
  repository_dispatch:
    types: [update-api-chart]

jobs:
  update-chart:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/event-platform-infra
          token: ${{ secrets.PAT_TOKEN }}
          path: infra

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Update Chart Version
        env:
          BRANCH: ${{ github.event.client_payload.branch }}
          SHA: ${{ github.event.client_payload.sha }}
          SHORT_SHA: ${{ github.event.client_payload.short_sha }}
          TAGS_JSON: ${{ github.event.client_payload.tags }}
        run: |
          cd infra/charts/event-api

          # Extract semver tags if available
          SEMVER_TAG=$(echo "$TAGS_JSON" | jq -r '.tags[] | select(startswith("v")) | gsub("^v"; "")' | sort -V | tail -n1)

          if [[ -n "$SEMVER_TAG" ]]; then
            # Use semver tag directly
            NEW_VERSION="$SEMVER_TAG"
            IMAGE_TAG="v$SEMVER_TAG"
          else
            # Increment patch version
            CURRENT_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
            IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
            PATCH=$((VERSION_PARTS[2] + 1))
            NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
            IMAGE_TAG="sha-${SHORT_SHA:0:7}"
          fi

          # Update Chart.yaml
          sed -i "s/^version:.*/version: $NEW_VERSION/" Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$IMAGE_TAG\"/" Chart.yaml

          # Update values.yaml
          sed -i "s/tag:.*/tag: $IMAGE_TAG/" values.yaml
